### ISSUE TITLE
problem while deploying L1P system

### ISSUE THREAD

**Issue by saminmun** [mojaloop/mojaloop#128]
Hello, 

I'm trying to deploy L1P system in my test environment. I'm following the steps mentioned in https://github.com/mojaloop/interop-devops, README.md.

I have a centos 7 host. The Vagrant version is "Vagrant 2.0.2" and VirtualBox Version is "Version 5.1.6".

As stated in the README.md file after setting up the network details in the Vagrant file I run the "vagrant up" command. The deployment process runs well until I get this error and deployment exits"

```
 mgmt: TASK [request_data : command] **************************************************
    mgmt:  [WARNING]: Consider using get_url or uri module rather than running curl
    mgmt: fatal: [mgmt]: FAILED! => {"changed": true, "cmd": "curl -X POST -H \"Authorization:Basic YWRtaW46YWRtaW4=\" --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{\"name\": \"dfsp1\",\"shortName\": \"dfsp1\",\"providerUrl\": \"http://192.168.0.150:8088/scheme/adapter/v1\"}' http://192.168.0.152:8088/mock/directory/v1/commands/register", "delta": "0:00:00.013631", "end": "2018-02-25 06:48:51.984925", "msg": "non-zero return code", "rc": 7, "start": "2018-02-25 06:48:51.971294", "stderr": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 192.168.0.152 port 8088: Connection refused", "stderr_lines": ["  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", "                                 Dload  Upload   Total   Spent    Left  Speed", "", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 192.168.0.152 port 8088: Connection refused"], "stdout": "", "stdout_lines": []}
    mgmt: 	to retry, use: --limit @/vagrant/create-local.retry
    mgmt: 
    mgmt: PLAY RECAP *********************************************************************
    mgmt: dfsp1                      : ok=35   changed=28   unreachable=0    failed=0   
    mgmt: dfsp2                      : ok=35   changed=28   unreachable=0    failed=0   
    mgmt: ist                        : ok=9    changed=7    unreachable=0    failed=1   
    mgmt: localhost                  : ok=26   changed=18   unreachable=0    failed=0   
    mgmt: mgmt                       : ok=16   changed=13   unreachable=0    failed=1   
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
The error says connection refused to 192.168.0.152 on port 8088. According to the Vagrant file the IP belongs to the "ist" sever.  When I checked the ist server I could not find any service running on port 8088. So, I'm not sure what service should be running on port 8088 for the ist server. 

I have tried the whole deplyment process for multiple times. But It get stuck on this issue.

It would be of great help if someone could help to figure out the issue.

Thanks in advance
